spring.application.name=Murty
spring.datasource.username=root
spring.datasource.password=techno
spring.datasource.url=jdbc:mysql://localhost/flm
server.port=9696
server.servlet.context-path=/employee
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

